services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: productdbs
      MYSQL_DATABASE: productsdatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: mounikav24/2300032943-exam-backend:final
    container_name: springboot
    ports:
      - "2025:2000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/productsdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: productdbs
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: mounikav24/2300032943-exam-frontend:final
    container_name: react
    ports:
      - "2001:80"
    environment:
      REACT_APP_API_URL: http://localhost:2025
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net: